# sources:
#   - <sources path>
#   - <sources path>
project:
  file: ../ProjectName.xcodeproj
  target:
    name: TargetName
    module: ModuleName
templates:
  include:
    - Templates/AutoReusableCell.swifttemplate
output:
    ../Generated
